// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvlhvurybzfbckylkygh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2bGh2dXJ5YnpmYmNreWxreWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3OTM5NjIsImV4cCI6MjA4ODM2OTk2Mn0.g03pH3j_VuRlHSXIgy9YecDWnJxf_3TQnKIw36vJD2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});